### ISSUE TITLE
[1.16.3] No tomb spawns when killed by explosions.

### ISSUE THREAD

**Issue by Gbergz** [Lothrazar/Tombstone-Fork#1]
Minecraft Version: **1.16.3**

Forge Version: **34.1.21**

Mod Version: **1.16.3-1.0.0**

Single Player or Server: Single Player & Server

Describe problem (what you were doing; what happened; what should have happened):
No tomb spawns when killed by any explosions.

Log file link:
[latest.log](https://github.com/Lothrazar/Tombstone-Fork/files/5405347/latest.log)

Video/images/gifs (direct upload or link): 
https://gyazo.com/2ef35326f3f7a2cb85f6ee2355139c39

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Tombstone-Fork/commit/40238755334c37e07f163c39d7835c3ae060ed80

**Comment by Lothrazar** [comment]
check out this release. The 4 grave blocks are now infiniburn_overworld and wither_immune, and shouldn't be destroyed by other things such as tnt and creeper explosions anymore  https://www.curseforge.com/minecraft/mc-mods/simple-tomb/files/3088400 

Open an issue anytime if you find something else
