### ISSUE TITLE
[Suggestion] Allow Grave to have a Hitbox to Place Blocks Against

### ISSUE THREAD

**Issue by Darkosto** [Lothrazar/Tombstone-Fork#10]
Minecraft Version: 1.16.5

Forge Version: 36.0.43

Mod Version: ${version}
Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):
The grave does not have a hitbox. Please add a hitbox so when I fall into the void I don't lose my stuff!

Also, hey! You do good work and are a good person. Keep on keepin on!
Log file link: "darkosto died in the void"

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

![image](https://user-images.githubusercontent.com/10309699/109402387-666d3900-790a-11eb-80bc-bb1a40d588a4.png)

**Comment by Lothrazar** [comment]
Nice picture!

Giving it a low hitbox, less than a slab so its buildable  

Also, you can stand on it now
![2021-02-27_15 07 13](https://user-images.githubusercontent.com/621529/109402793-9c5fec80-790d-11eb-8c18-3874074d1878.png)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-tomb/files/3221199
