### ISSUE TITLE
[1.16.3] Water Color changes when looking in certain directions when a grave is on the ground.

### ISSUE THREAD

**Issue by Gbergz** [Lothrazar/Tombstone-Fork#2]
Minecraft Version: **1.16.3**

Forge Version: **34.1.21**

Mod Version: [1.0.1](https://www.curseforge.com/minecraft/mc-mods/simple-tomb/files/3088400)

Single Player or Server: **SP & MP**

Describe problem (what you were doing; what happened; what should have happened):
When you've died and a grave spawns the water color changes when looking in certain directions around the water. It's like flickering back and forth between two shades of blue. Gif below will explain it better.

GIF Showing it in action: 
https://gyazo.com/96cc0ae212527a25f82c852ec6b8ca0e

EDIT: And while I'm here I'll report this.
![image](https://user-images.githubusercontent.com/26634554/96702578-2f9e7980-1392-11eb-92c9-2571257cb58e.png)

Doesn't seem like that text is translated or whatever. Minor issue might aswell report it.

**-** Gbergz

**Comment by Lothrazar** [comment]
Fixed the lang issue.

For the water issue, i cant replicate it the way thee GIF shows, but i have seen that exact issue with other mods and ive tried to fix it before.  (Well, maybe its only certain grave blocks / grave types, i only tried a few)  Theres nothing i can really do, its just how the water works deep down in the minecraft openGL source

**Comment by Lothrazar** [comment]
I tweaked rendering a little bit, and it does look better. but most of this is out of my control https://www.curseforge.com/minecraft/mc-mods/simple-tomb/files/3139875
