### ISSUE TITLE
Graves Spawn Below Y=0

### ISSUE THREAD

**Issue by Darkosto** [Lothrazar/Tombstone-Fork#4]
Minecraft Version: 1.16.4

Forge Version: 35.1.0

Mod Version: ${version}

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

1. Fall down in void to death!
2. Grave spawns a few blocks below 0
3. You're unable to build off of it to recover your items (this would honestly be very helpful in sky block type worlds)

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Looking into this now, must have missed the notification when it was created

**Comment by Lothrazar** [comment]
Adding features where 
-it cannot spawn at y=0, minimum is y=1
- if possible it first searches for a spot where the block below is solid, if possible. if not found it will still spawn in midair at y=1.

Going to do lots of testing tomorrow.  The search range is not in config yet so ill look into that,  and also Ive noticed it wont place graves under water so ill add that as well.  


before dying at -200 in the void did this as you saw
![before](https://user-images.githubusercontent.com/621529/102171653-ea576f00-3e4b-11eb-9cb1-f323ddcc15ee.png)

After the fix it finds the stone block 

![after](https://user-images.githubusercontent.com/621529/102171740-170b8680-3e4c-11eb-9ec8-d267377a2c1e.png)

**Comment by Lothrazar** [comment]
Latest update improves much of this :) 



Feature: Grave is now able to spawn underwater.

 

Feature: If you die in midair, it searches for a solid block to place the grave on.

 

Feature: The distance from the player to search for a valid grave location is now in the config file.

 

When you pickup a grave, fixed issue where the item slot where the key was never gets filled.

 

Fix a bug where you would get 'there was nowhere to place the grave' if you died deep down in the void.

 

Fix a bug where graves were spawning at y=0, meaning you cannot place a block underneath it (minimum is now y=1).

 

New configs added to control the searching range when its looking for a grave spawn point.

 

New optimization feature: if the death point is a valid grave placement, it places there and does not search around.



https://www.curseforge.com/minecraft/mc-mods/simple-tomb/files/3139875
