### ISSUE TITLE
Can't see my grave

### ISSUE THREAD

**Issue by luluidek** [Lothrazar/Tombstone-Fork#5]
Minecraft Version: 1.16.4

Forge Version: 35.1.13

Mod Version: simpletomb-1.16.4 - 1.0.3

Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened):
I teleported to a friend that was dying on lava, we both died and had to then cover the lava to get to our graves. He could see and interact with his, but i couldn't with mine. 
I could only see a highlighted cube and the indication that i died there but when i tried to retrieve my things, after the shining stuff nothing happened. 
I think the grave bugged maybe? 

Log file link:

Video/images/gifs (direct upload or link): https://imgur.com/O6aSMpn

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

Thank You!

**Comment by Lothrazar** [comment]
Thanks for the imgur and everything.  do you have any logs from when you died, like server logs. also does sneaking anywhere in that area trigger the grave.

the lava shouldnt be able to replace the gravestone but ill test that out. was their grave a few blocks away like pretty close?

**Comment by SheroxGG** [comment]
Something similar happened to a user from my server last night. I am on 1.12.2. Using the key highlights a block but the tomb is not there. He tried sneaking and everything but didnt work. And there are not any logs, just a normal log saying tomb created. I have checked the server logs.

**Comment by Lothrazar** [comment]
made some updates to 1.16 ; also you have a 

/simpletomb latest

command in case you lose your key it says the position. still WIP
