### ISSUE TITLE
[Request] Place Curios etc in correct slots when opening Tomb

### ISSUE THREAD

**Issue by NillerMedDild** [Lothrazar/Tombstone-Fork#8]
Armor is already placed in the correct slots when the Tomb is opened, could the same perhaps be done for Curios?

**Comment by theboo** [comment]
Curios* :P

**Comment by theboo** [comment]
looks like corail has this already and just needs ported xD

https://github.com/Darkhax/Corail-Tombstone/search?q=curio&type=

**Comment by NillerMedDild** [comment]
@Lothrazar ping just in case you don't have notifications for this repo either :P

**Comment by Lothrazar** [comment]
Almost done. just trying to find out how to match curios to their valid slots.  pushed code allows gloves into ring slots , need a new strategy https://github.com/TheIllusiveC4/Curios/issues/107

**Comment by NillerMedDild** [comment]
Thanks for the update 👍

**Comment by Lothrazar** [comment]
Worked in my handful of tests with gloves and boots and rings items. lmk if its broken https://www.curseforge.com/minecraft/mc-mods/simple-tomb/files/3201800

**Comment by NillerMedDild** [comment]
It works, thank you \o/
