### ISSUE TITLE
[suggestion] Place dirt block under grave in void.

### ISSUE THREAD

**Issue by theboo** [Lothrazar/Tombstone-Fork#9]
currently if you die in the void, it places the grave at y=1, but you cannot place a block on the grave. as it doesnt seem to be a valid target to place a block on. Would be nice if there is no solid blocks in range that the grave generates a dirt block underneath so you can have something to build around so you dont lose items if your inventory cant handle everything from your grave. 

Either that or make the grave a valid target to place blocks on/make it solid. (once in testing i was able to get a block to place on top of the grave but havent been able to since then)

**Comment by Lothrazar** [comment]
Good idea, and it makes sense.

Instead, i gave the grave a hitbox, so you can build and place against it.  Also, you can now stand on top of it like a solid carpet  
![2021-02-27_15 08 44](https://user-images.githubusercontent.com/621529/109402815-bef20580-790d-11eb-9121-33082f035765.png)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-tomb/files/3221199

**Comment by theboo** [comment]
Perfect, thanks!
